### ISSUE TITLE
csort help documentation wrong?

### ISSUE THREAD

**Issue by larrypl** [aspiers/shell-env#3]
I think `N=/regex/ `should be `N=/string/`?

**Comment by aspiers** [comment]
Wow, I'd totally forgotten I ever wrote this.  Amazingly it was exactly 10 years ago today!

Thanks for the report; looking at the code, I think it should actually be `N=string`.  I'll fix.

**Comment by larrypl** [comment]
Thanks for the update! And the anniversary for csort!

**Comment by aspiers** [comment]
You're welcome! How on earth did you find it, though, when I couldn't even remember it existed? :rofl:

**Comment by larrypl** [comment]
I was looking for a way to sort dev, qa, stage, prod in that order (rather than dev, prod, qa, stage) and came across a stackexchange entry where you posted (10 years ago, IIRC) that you had written csort for that purpose. So now I can sort system names by their respective environments in logical order, because of csort!
I'll find the entry if you're interested.

**Comment by larrypl** [comment]
This is my use:
```
csort -t$'\t' 2:/^dev/ 1 2:/^qa/ 2 2:/^stage/ 3 2:/^prod/ 4
```

**Comment by aspiers** [comment]
Ah yes, found it: https://superuser.com/a/602918/104997

Again, zero recollection of this.  I'm old enough that the internet has become the swap space for my brain :man_facepalming: :laughing:

**Comment by larrypl** [comment]
Ha! Me too.
